title: Procesamiento de imágenes
description: Análisis de imágenes/videos al implementar operaciones tanto por software como por hardware
show_downloads: true
google_analytics:
theme: jekyll-theme-cayman